/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SupporterService } from "../supporter.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SupporterCreateInput } from "./SupporterCreateInput";
import { Supporter } from "./Supporter";
import { SupporterFindManyArgs } from "./SupporterFindManyArgs";
import { SupporterWhereUniqueInput } from "./SupporterWhereUniqueInput";
import { SupporterUpdateInput } from "./SupporterUpdateInput";
import { DonationFindManyArgs } from "../../donation/base/DonationFindManyArgs";
import { Donation } from "../../donation/base/Donation";
import { DonationWhereUniqueInput } from "../../donation/base/DonationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SupporterControllerBase {
  constructor(
    protected readonly service: SupporterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Supporter })
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSupporter(
    @common.Body() data: SupporterCreateInput
  ): Promise<Supporter> {
    return await this.service.createSupporter({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Supporter] })
  @ApiNestedQuery(SupporterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async supporters(@common.Req() request: Request): Promise<Supporter[]> {
    const args = plainToClass(SupporterFindManyArgs, request.query);
    return this.service.supporters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Supporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async supporter(
    @common.Param() params: SupporterWhereUniqueInput
  ): Promise<Supporter | null> {
    const result = await this.service.supporter({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Supporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSupporter(
    @common.Param() params: SupporterWhereUniqueInput,
    @common.Body() data: SupporterUpdateInput
  ): Promise<Supporter | null> {
    try {
      return await this.service.updateSupporter({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Supporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSupporter(
    @common.Param() params: SupporterWhereUniqueInput
  ): Promise<Supporter | null> {
    try {
      return await this.service.deleteSupporter({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/donations")
  @ApiNestedQuery(DonationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "any",
  })
  async findDonations(
    @common.Req() request: Request,
    @common.Param() params: SupporterWhereUniqueInput
  ): Promise<Donation[]> {
    const query = plainToClass(DonationFindManyArgs, request.query);
    const results = await this.service.findDonations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        donationDate: true,
        amount: true,

        supporter: {
          select: {
            id: true,
          },
        },

        reason: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "update",
    possession: "any",
  })
  async connectDonations(
    @common.Param() params: SupporterWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        connect: body,
      },
    };
    await this.service.updateSupporter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "update",
    possession: "any",
  })
  async updateDonations(
    @common.Param() params: SupporterWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        set: body,
      },
    };
    await this.service.updateSupporter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Supporter",
    action: "update",
    possession: "any",
  })
  async disconnectDonations(
    @common.Param() params: SupporterWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        disconnect: body,
      },
    };
    await this.service.updateSupporter({
      where: params,
      data,
      select: { id: true },
    });
  }
}
